name: CI Elixir
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs: 
  ci:
    runs-on: ubuntu-latest 
    name: Compile with mix test, format, dialyzer & unused deps check
    env:
      MIX_ENV: test
    services:
      postgres:
        image: postgres:15.8
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - name: Setup Elixir
        uses: erlef/setup-beam@v1.17.3 
        with:
          version-file: .tool-versions 
          version-type: strict
      - name: Cache deps directory
        uses: actions/cache@v4
        id: cache-deps
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }} 
          restore-keys: |
            ${{ runner.os }}-mix-
      - name: Get dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: mix deps.get

      - run: mix compile --warnings-as-errors

      - name: Verify that DB migrations can rollback
        run: mix ecto.create && mix ecto.migrate && mix ecto.rollback --all

      - name: Run tests and check coverage
        run: mix coveralls

      - name: Check the code is formatted
        run: mix format --check-formatted

      - name: Check credo lint
        run: mix credo --strict

      - name: Cache plt files 
        uses: actions/cache@v4 
        env:
          EX_OTP_VERSIONS: ${{ steps.setup-beam.outputs.elixir-version }}
          KEY_BASE: plt-${{ runner.os }}-${{ env.EX_OTP_VERSIONS }} 
        with:
          path: |
            priv/plts
          key: |
            ${{ env.KEY_BASE }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ env.KEY_BASE }}-
      - name: Dialyzer static analysis 
        run: mix dialyzer --format github

      - name: Sobelow security static analysis
        run: mix sobelow --config

      - name: Check unused dependencies 
        run: mix deps.unlock --check-unused
  